n=int(input('Digite um numero pra ver sua tabuada:'))
print('-'*12)
print('{}x{}  = {}'.format(n, 1, 1*n))
print('{}x{}  = {}'.format(n, 2, 2*n))
print('{}x{}  = {}'.format(n, 3, 3*n))
print('{}x{}  = {}'.format(n, 4, 4*n))
print('{}x{}  = {}'.format(n, 5, 5*n))
print('{}x{}  = {}'.format(n, 6, 6*n))
print('{}x{}  = {}'.format(n, 7, 7*n))
print('{}x{}  = {}'.format(n, 8, 8*n))
print('{}x{}  = {}'.format(n, 9, 9*n))
print('{}x{} = {}'.format(n, 10, 10*n))
print('-'*12)

